### ISSUE TITLE
Unit tests timeout on CI has been detected

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-smart-proxy#166] opened 2020-08-04 07:35 UTC
```
{"level":"error","error":"the parameters contains invalid characters and cannot be used","time":"2020-08-04T07:33:24Z","message":"handleServerError()"}

{"level":"error","error":"listen tcp: address 99999: invalid port","time":"2020-08-04T07:33:24Z","message":"Unable to start HTTP/S server"}

--- FAIL: TestHTTPServer_ReportEndpoint (10.00s)

    timeout.go:39: Test ran out of time

{"level":"error","time":"2020-08-04T07:33:34Z","message":"This organization is not allowed to access this recommendation"}

{"level":"error","error":"This organization is not allowed to access this recommendation","time":"2020-08-04T07:33:34Z","message":"handleServerError()"}

{"level":"error","time":"2020-08-04T07:33:34Z","message":"Invalid/Malformed auth token"}

{"level":"error","error":"Invalid/Malformed auth token","time":"2020-08-04T07:33:34Z","message":"handleServerError()"}

{"level":"error","time":"2020-08-04T07:33:34Z","message":"This organization is not allowed to access this recommendation"}
```

**Comment by Sergey1011010** [comment] 2020-08-24 08:49
Does it happen each time or just randomly?

**Comment by Sergey1011010** [comment] 2020-09-02 12:45
How do you reproduce the issue? I can't do it on my local machine

**Comment by Sergey1011010** [comment] 2020-09-15 09:53
Closing because it's not reproducible.

**Closed by Sergey1011010** 2020-09-15 09:53 UTC
Labels: bug
